#include "GameplayTypes/Tags/Tactical/AbilityTags.h"

UE_DEFINE_GAMEPLAY_TAG(TAG_ABILITY_AUTOATTACK,   "Ability.AutoAttack")
UE_DEFINE_GAMEPLAY_TAG(TAG_ABILITY_MOVEMENT,     "Ability.Movement")
UE_DEFINE_GAMEPLAY_TAG(TAG_ABILITY_WAIT,         "Ability.Wait")
UE_DEFINE_GAMEPLAY_TAG(TAG_ABILITY_DEFEND,       "Ability.Defend")
UE_DEFINE_GAMEPLAY_TAG(TAG_ABILITY_FLEE,         "Ability.Flee")
UE_DEFINE_GAMEPLAY_TAG(TAG_ABILITY_SPELL,        "Ability.Spell")
UE_DEFINE_GAMEPLAY_TAG(TAG_ABILITY_SPELL_SUMMON, "Ability.Spell.Summon")

UE_DEFINE_GAMEPLAY_TAG(TAG_ABILITY_ATTACK,  "Ability.Intent.Attack")
UE_DEFINE_GAMEPLAY_TAG(TAG_ABILITY_HEAL,    "Ability.Intent.Heal")
UE_DEFINE_GAMEPLAY_TAG(TAG_ABILITY_BUFF,    "Ability.Intent.Buff")
UE_DEFINE_GAMEPLAY_TAG(TAG_ABILITY_DEBUFF,  "Ability.Intent.Debuff")
UE_DEFINE_GAMEPLAY_TAG(TAG_ABILITY_EFFECT,  "Ability.Intent.Effect")
