#pragma once
#include "CoreMinimal.h"
#include "GameplayTags.h"
#include "NativeGameplayTags.h"
#include "GameplayTagsManager.h"

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ABILITY_AUTOATTACK)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ABILITY_MOVEMENT)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ABILITY_WAIT)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ABILITY_DEFEND)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ABILITY_FLEE)
