"""
Walks Content/Fab and produces Fab_manifest.txt: one entry per redownloadable
FAB module, with a Link field to fill in by hand.

FAB module content is gitignored (see .gitignore) - only this manifest and the
empty folder skeleton (.gitkeep files) are tracked, so a fresh clone can
reconstruct the folder layout and tells you what to redownload.

A folder is either:
  - "skeleton": a purely organizational wrapper you created (e.g. "Animation"),
    which the script recurses into looking for modules.
  - "module": the root of one actual downloaded FAB pack. Everything below it
    belongs to that one module; the script does not recurse further.

Classification is not guessed from folder names/depth - it's read from
fab_manifest_config.json next to this script. Any folder not yet classified
is asked about interactively and the answer is persisted.

Usage: python generate_fab_manifest.py
"""
import json
import sys
from pathlib import Path

CONTENT_DIR = Path(__file__).resolve().parent
FAB_DIR = CONTENT_DIR / "Fab"
CONFIG_PATH = CONTENT_DIR / "fab_manifest_config.json"
MANIFEST_PATH = CONTENT_DIR / "Fab_manifest.txt"


def load_config():
    if CONFIG_PATH.exists():
        data = json.loads(CONFIG_PATH.read_text(encoding="utf-8"))
    else:
        data = {}
    data.setdefault("skeleton", [])
    data.setdefault("module", [])
    return data


def save_config(config):
    ordered = {
        "skeleton": sorted(set(config["skeleton"])),
        "module": sorted(set(config["module"])),
    }
    CONFIG_PATH.write_text(json.dumps(ordered, indent=2) + "\n", encoding="utf-8")


def classify(rel_path, config, known):
    if rel_path in known:
        return known[rel_path]

    abs_dir = FAB_DIR / rel_path
    children = sorted(p.name for p in abs_dir.iterdir() if p.is_dir())
    print(f"\nUnclassified folder: Fab/{rel_path}")
    if children:
        print("  subfolders: " + ", ".join(children))
    else:
        print("  (no subfolders)")

    while True:
        answer = input("  Is this a [s]keleton (organizational) or [m]odule (one FAB pack)? ").strip().lower()
        if answer in ("s", "skeleton"):
            choice = "skeleton"
            break
        if answer in ("m", "module"):
            choice = "module"
            break
        print("  Please answer 's' or 'm'.")

    config[choice].append(rel_path)
    known[rel_path] = choice
    save_config(config)
    return choice


def collect_modules(config):
    known = {}
    for kind in ("skeleton", "module"):
        for rel_path in config[kind]:
            known[rel_path] = kind

    modules = []

    def walk(rel_path):
        kind = classify(rel_path, config, known)
        if kind == "module":
            modules.append(rel_path)
            return
        abs_dir = FAB_DIR / rel_path if rel_path else FAB_DIR
        for child in sorted(p for p in abs_dir.iterdir() if p.is_dir()):
            child_rel = f"{rel_path}/{child.name}" if rel_path else child.name
            walk(child_rel)

    abs_root = FAB_DIR
    for child in sorted(p for p in abs_root.iterdir() if p.is_dir()):
        walk(child.name)

    return modules


def parse_existing_manifest():
    """Returns {module_path: link} for links already filled in."""
    links = {}
    if not MANIFEST_PATH.exists():
        return links
    current = None
    for line in MANIFEST_PATH.read_text(encoding="utf-8").splitlines():
        line = line.rstrip()
        if line.startswith("Module: "):
            current = line[len("Module: "):].strip()
        elif line.startswith("Link: ") and current is not None:
            link = line[len("Link: "):].strip()
            if link:
                links[current] = link
            current = None
    return links


def write_manifest(modules, existing_links):
    lines = [
        "# FAB module manifest - auto-generated by generate_fab_manifest.py",
        "# Fill in the Link field for each module so a re-installed project knows what to redownload.",
        "# Re-running the script preserves any links you've already filled in.",
        "",
    ]
    for module in sorted(modules):
        lines.append(f"Module: {module}")
        lines.append(f"Link: {existing_links.get(module, '')}")
        lines.append("")

    missing = sorted(set(existing_links) - set(modules))
    for module in missing:
        lines.append(f"Module: {module}  [MISSING FROM DISK]")
        lines.append(f"Link: {existing_links[module]}")
        lines.append("")

    MANIFEST_PATH.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def create_gitkeeps():
    count = 0
    for d in FAB_DIR.rglob("*"):
        if d.is_dir():
            keep = d / ".gitkeep"
            if not keep.exists():
                keep.touch()
                count += 1
    return count


def main():
    if not FAB_DIR.is_dir():
        print(f"error: {FAB_DIR} does not exist", file=sys.stderr)
        sys.exit(1)

    config = load_config()
    modules = collect_modules(config)
    existing_links = parse_existing_manifest()
    write_manifest(modules, existing_links)
    keep_count = create_gitkeeps()

    print(f"\n{len(modules)} module(s) written to {MANIFEST_PATH.relative_to(CONTENT_DIR.parent)}")
    print(f"{keep_count} new .gitkeep file(s) created")


if __name__ == "__main__":
    main()
